platform :ios,'7.0'
pod 'SDWebImage','~>3.7'
pod "AFNetworking", "~> 2.0"
pod 'SWTableViewCell', '~> 0.3.7'
pod 'TPKeyboardAvoiding','~>1.2.6'
pod 'X_TableView', :git => 'https://github.com/fc01/X_TableView.git', :tag => '0.11'
pod 'EDStarRating'
pod 'FMDB'
pod 'YTKKeyValueStore'
pod 'SFTagView'